

Ajoutez un commentaireโฆ


Omar Lotfy
il y a 1 mois
ุงูุช ุจุฑูุณ ูุงููู ูุน ุงูู ูุฌุฑุจุชุด ุงูุฎุทูุงุช ุจุณ ุงูุง ุนุงุฑู ุดุบูู ... ุงุณุชูุฑ ูุง ุตุฏููู ูุงู ุดุงุก ุงููู ุงุดููู ุงูุจุฑ ููุงุฉ ุนูู ุงูููุชููุจ

2
1



Funny Cats
il y a 1 mois
ุดูุฑุง

1




Funny Cats
il y a 1 mois
ุดูุฑุง ูุงููู

2




Funny Cats
il y a 1 mois
ุดูุฑุง ููุง ูููุจ

1




wight lose steps
il y a 1 mois
ููููู ูููุข ุขุถูุบุทู ุนูู action ู ci ูุจููุนุฏุข ุขุดูุบ ููู ูู ุขูุฎูุขูุฉ ููุขูุจููู ุขูุขุฎููุฑุฉ ููููู  ุขุณูููู ูููุฒุฑ ุจููุขูุขุญูููุฑ ูู ูุฌุจ ูุชุบููุฑ ุงูุงุณู ููููุฉ ุงููุฑูุฑ ูุตุงุญุจ ุงูุญุณุงุจ

1
1



ูุฑูุด ูุชุณูุง
il y a 1 mois
ููุฐุช ุฌููุน ุงูุฎุทูุงุช ููุงุทูุน ุงู ุดู ๐ช

1
1



Funny Cats
il y a 1 mois
ุฅุนุทููุง rdp ุจููุฒ

2




Funny Cats
il y a 1 mois
ุนููุชู rdp

1




ุจูุง ููุง ุจูู
il y a 1 mois
ูุถูุฑ ูู ูุฏุง Workflows arenโt being run on this repository
ุนูุฏูุง ุงุถุบุท ุนูู action

1
3



BASSEM TECHNOLOGY
il y a 1 mois
ุจููููู ููุฐ ุฎุทุง Create blank.yml ุงูุดุฑุญ ุงูู ูู ุงูุฏูููู 9:52

1
6



Gigkhhi Eghki
il y a 1 mois
ุจุนุฏ ุฏูููุฉ ุจููุญุถุฑ ุญุณุงุจู ูู github

3




munzer khlailate
il y a 1 mois
CI: All jobs have failed
ูุด ุดุบู ูุจุฏููู ูุณุฌ ุน ุงูุฌูููู

1
2



เค เค เค เค เค เค เค เค เค เค เค เค เคก เคข เคฃ เคคเคพ เคฅ เคฆ เคง เคจ เคช เคซ เคฌ เคญ
il y a 1 mois
Work for 1 hour?

1
1



Funny Cats
il y a 1 mois
ูููู ูุฑุญุงููู

2




Gigkhhi Eghki
il y a 1 mois
ุงุฎู ุจุทูุจ ููู ุทูุจ ุณุฃูุดุก ุญุณุงุจ ุฌุฏูุฏ ูู github ูุญุณุงุจ ูู ngrok ูุงุนุชูู ุญุณุงุจุงุชู ุงุญุชุงุฌ ููู ุชุฏุฎู ูู ุงูููู ุนูุฏู ูุดููุฉ ูู ุงูููู

1
2



Funny Cats
il y a 1 mois
ูุดููุฉ ูู ngrok

2
3




Funny Cats
il y a 1 mois
ูููู ุฅูุง ูุญุชุงุฌูู

1




Funny Cats
il y a 1 mois
ุฅุจุนุชูู ุฃุฑุฌูู ูุง ุตุงุญุจู

1




Ali Mohamed
il y a 1 mois
ููู ูููู ุงุดุชุฑู ููุงุตูุงุช ุงุนูู ุ

1
1



Gigkhhi Eghki
il y a 1 mois
ูุน ูู ุงุญุชุฑุงูู ุงูููู ุบูุฑ ุดุบุงู ูู ุงูุฎุงูุฉ ูุง ูุจู ุงูุงุฎูุฑุฉ ูุนุชููู ุนูุงูุฉ ุญูุฑุงุก

1
3



Funny Cats
il y a 1 mois
ุดูุฑุง

1




GoGo YT !
il y a 1 mois
ููููู ูููุข ุขุถูุบุทู ุนูู action ู ci ูุจููุนุฏุข ุขุดูุบ ููู ูู ุขูุฎูุขูุฉ ููุขูุจููู ุขูุขุฎููุฑุฉ ููููู  ุขุณูููู ูููุฒุฑ ุจููุขูุขุญูููุฑ

2
5



men in the game
il y a 1 mois
ุทุจ ุงูุง ูุด ุนุงุฑู ุงุนููู ุนูุดุงู ุงูููุจุงูู ููููุนุด ููู

2



King SY
il y a 1 mois
ุบูุฑ ุตุญูุญ ูุงูุนูู ุณูู ูุงููู

1
1



loki loki
il y a 9 jours
ูุนู ุทุฑููุชู ุตุญูุญู ุจุณ ุงูุฒูู ูุตูุฑ ุงูุช ูุงูู ุณูู ุ

1
2



Funny Cats
il y a 1 mois
ุฅุจุนุชูู ูุง ุตุงุญุจู

1




Eslam Fadl
il y a 1 mois
ุงุดุชุบู ุจุณ 5 ุฏูุงุฆู ูุจููุตู
ููุจูุฏุฎูุด ุชุงูู 
ุนููุช ุงูุชุฑ ูู ูุงุญุฏ ููุณ ุงูุญูุงูุฉ

2
4



Terminator TECH | ุงููุฏูุฑ ุชููู
il y a 1 mois
ุนุงูู ุงูุงูููุช ุจุงูุฌูููู




Eslam Fadl
il y a 1 mois
 @Terminator TECH | ุงููุฏูุฑ ุชููู  ุงููู




Eslam Fadl
il y a 1 mois
 @Terminator TECH | ุงููุฏูุฑ ุชููู  ุ

1



Terminator TECH | ุงููุฏูุฑ ุชููู
il y a 1 mois
 @Eslam Fadl  ุงุณุชุฎุฏู ุฏุฉ
name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
